nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:4200']  # Tu front-end
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
    paths:
        '^/api/': ~
