security:
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto

    providers:
        usuarios:
            entity:
                class: App\Entity\Usuario
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern: ^/api/register$
            stateless: true
            security: false  # Desactivar la seguridad para esta ruta

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/  # Rutas para desarrollo sin seguridad
            security: false

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Login sin autenticación
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Registro sin autenticación
        - { path: ^/api, roles: ROLE_USER }  # Otras rutas de la API requieren autenticación
